services:
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql
      - ./server/scripts:/docker-entrypoint-initdb.d:ro
volumes:
  db: