services:
  mysql:
    image: mysql:9.1.0
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./server/scripts:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./server/.env
volumes:
  db: